version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - 8000:8000
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=ferre
            - DB_USERNAME=admin
            - DB_PASSWORD=pwdroot
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: pwdroot
            MYSQL_DATABASE: ferre
            MYSQL_USER: admin
            MYSQL_PASSWORD: pwdroot
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - 3306:3306

volumes:
    dbdata:
